from __future__ import annotations

import time
from pathlib import Path

from . import config


def profile_dir() -> Path:
    return config.DATA_DIR / "browser-profile"


def exported_cookies_path() -> Path:
    return config.DATA_DIR / "private" / "playzi_browser_cookies.txt"


def export_cookies(headless: bool = True) -> Path:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise RuntimeError("Playwright no esta instalado. Ejecuta: pip install playwright") from exc

    profile_dir().mkdir(parents=True, exist_ok=True)
    exported_cookies_path().parent.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            str(profile_dir()),
            headless=headless,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
        )
        page = context.pages[0] if context.pages else context.new_page()
        page.goto("https://www.youtube.com/", wait_until="domcontentloaded", timeout=30000)
        page.wait_for_timeout(1500)
        cookies = context.cookies(["https://www.youtube.com", "https://music.youtube.com", "https://google.com"])
        context.close()

    if not _has_login_cookie(cookies):
        raise RuntimeError(
            "El perfil administrado de Playzi no tiene sesion de YouTube. "
            "Ejecuta scripts\\login-youtube.ps1 e inicia sesion una vez."
        )

    _write_netscape_cookie_file(exported_cookies_path(), cookies)
    return exported_cookies_path()


def _has_login_cookie(cookies: list[dict]) -> bool:
    names = {cookie.get("name") for cookie in cookies}
    return bool({"SAPISID", "__Secure-1PAPISID", "__Secure-3PAPISID"} & names)


def _write_netscape_cookie_file(path: Path, cookies: list[dict]) -> None:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Playzi managed browser",
    ]
    for cookie in cookies:
        domain = cookie.get("domain") or ""
        if "youtube.com" not in domain and "google.com" not in domain:
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        cookie_path = cookie.get("path") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = int(cookie.get("expires") or 0)
        if expires < 0:
            expires = int(time.time()) + 24 * 60 * 60
        name = cookie.get("name") or ""
        value = cookie.get("value") or ""
        if not name:
            continue
        lines.append("\t".join([domain, include_subdomains, cookie_path, secure, str(expires), name, value]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def open_login_browser() -> None:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise RuntimeError("Playwright no esta instalado. Ejecuta: pip install playwright") from exc

    profile_dir().mkdir(parents=True, exist_ok=True)
    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            str(profile_dir()),
            headless=False,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
        )
        page = context.pages[0] if context.pages else context.new_page()
        page.goto("https://accounts.google.com/ServiceLogin?service=youtube", wait_until="domcontentloaded")
        print("Inicia sesion en la ventana de Chromium de Playzi.")
        print("Cuando termines, cierra esa ventana para guardar la sesion.")
        while True:
            try:
                if not context.pages:
                    break
                context.pages[0].wait_for_timeout(1000)
            except Exception:
                break
